apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: job-orchestrator-server-data
  labels:
    app: job-orchestrator
    component: server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: job-orchestrator-client-data
  labels:
    app: job-orchestrator
    component: client
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
